<h1><?=$this->message?></h1>
<table>
    <tr>
        <td><strong>Message:</strong></td>
        <td><?=$this->message?></td>
    </tr>
    <tr>
        <td><strong>Type:</strong></td>
        <td><?=$this->type?></td>
    </tr>
    <tr>
        <td><strong>File:</strong></td>
        <td><?=$this->file?></td>
    </tr>
    <tr>
        <td><strong>Line:</strong></td>
        <td><?=$this->line?></td>
    </tr>
</table>